export const swaggerController = {
    auth:" Auth",
    company:" Company",
    user:" User",
    roles:" Roles",
    permission:" Permission",
    category:" Category",
    brand:" Brands",
    units:" Units",
    customer:" Customer",
    vendor:" Vendors",
    product:" Product",
    purchase:" Purchase",
    sales:" Sales",
    report:" Report",
}